### ISSUE TITLE
Again. xbps destroy links in root [BUG]

### ISSUE THREAD

**Issue by Bezzumnbiu** [void-linux/xbps#513] opened 2022-10-03 18:56 UTC
XBPS: 0.59.1 API: 20200221

if you create a package with a program from a folder similar to root, that is, where there is / bin / lib / sbin, etc., then xbps-install will remove the references and simply create these folders again

How to repeat this experiment:

    Create in the folder that will become the basis for xbps-create, folders / bin / lib / sbin
    Throw any files into them
    Collecting the package
    Install the package on the system
    ???
    Congratulations, you have killed the links in your root section.

Of course, you can just create a normal directory tree and make sure that all packages are installed in directories that are not made as links in the system ... But I alone think that this should not be so?

**Comment by Duncaen** [comment] 2022-10-03 20:28
This is basically a duplicate of https://github.com/void-linux/xbps/issues/287, xbps does not do full conflict checks with already installed packages. Until this is fixed/changed, this is a packaging error.

**Closed by Duncaen** 2022-10-03 20:29 UTC
