### ISSUE TITLE
`xbps-query -o` does not follow symlinks

### ISSUE THREAD

**Issue by camoz** [void-linux/xbps#485] opened 2022-04-20 08:45 UTC
Not sure if this is a bug or intended behavior.

```
[m@void ~]$ ls -la /bin
lrwxrwxrwx 1 root root 7 May  4  2021 /bin -> usr/bin
[m@void ~]$ xbps-query -o /bin/test
[m@void ~]$ echo $?
0
[m@void ~]$ xbps-query -o /usr/bin/test
coreutils-8.32_4: /usr/bin/test (regular file)
[m@void ~]$ 
```

**Comment by camoz** [comment] 2022-04-21 07:10
On IRC I learned that `xbps-query -o` does not look at the filesystem at all but uses an internal list of files, so symlinks can never be resolved at runtime.

Then it should probably be modified to also consider paths which are in `PATH`, which is modified by voidlinux in `/etc/profile`:

```
# Set our default path (/usr/sbin:/sbin:/bin included for non-Void chroots)
appendpath '/usr/local/sbin'
appendpath '/usr/local/bin'
appendpath '/usr/bin'
appendpath '/usr/sbin'
appendpath '/sbin'
appendpath '/bin'
```

**Comment by Vaelatern** [comment] 2022-04-21 16:00
How do you imagine the ergonomics working out, with xbps-query -o not looking in $PATH now, but looking for specific file paths?

Better imo to run `xlocate bin/test`

**Comment by camoz** [comment] 2022-04-21 16:23
I'm sorry I don't understand your question...

**Comment by illiliti** [comment] 2022-06-26 23:46
Duplicate of https://github.com/void-linux/xbps/issues/210

**Closed** 2022-06-27 11:47 UTC
