### ISSUE TITLE
Empty directories don't get removed on xbps-remove

### ISSUE THREAD

**Issue by steinex** [void-linux/xbps#23] opened 2018-10-14 10:57 UTC
When deinstalling a package, empty directories that were created by the package on installation are left behind.

For example, `cmus` leaves `/usr/lib/cmus`.
Another: `faenza-icon-theme` leaves `/usr/share/icons/Faenza*`.

It's not so that every directory is left behind, though. In the cmus example, `/usr/share/cmus` is properly cleaned up. I can't see a pattern in which case a directory is deleted and in which not.

It seems not to be package specific.

**Comment by Vaelatern** [comment] 2018-10-14 13:51
Seems interesting, `/usr/lib/cmus` is itself only home to two separate directories, `op` and `ip`.
@steinex please clarify: which dirs in `faenza-icon-theme` are left behind?

**Comment by steinex** [comment] 2018-10-14 14:36
```
/usr/share/Faenza
/usr/share/Faenza-Ambiance
/usr/share/Faenza-Dark
/usr/share/Faenza-Darker
/usr/share/Faenza-Darkest
/usr/share/Faenza-Radiance
```

kitty is another example, it leaves:
```
/usr/lib/kitty
/usr/lib/kitty/kittens
/usr/lib/kitty/kitty
/usr/lib/kitty/terminfo
```

**Comment by biopsin** [comment] 2018-11-13 08:46
/usr/lib/ImageMagick-7.0.8 - a subfolder "modules-Q16HDRI" blocks the removal

**Comment by Vaelatern** [comment] 2018-11-13 14:06
But it's not just subfolders. As best I can tell, `/usr/share/Faenza-Radiance` has no subfolders, just files.

**Comment by jnbr** [comment] 2018-11-13 14:29
There is no `/usr/share/Faenza-Radiance` at all in `faenza-icon-themes`. It's all in `/usr/share/icons/Faenza*`

**Comment by steinex** [comment] 2018-11-13 14:33
Yes, this was my error, sorry. The above listing of mine for `faenza-icon-themes` misses `/icons/`. However, it was just an example anyway as the issue applies to all packages and still stands.

**Comment by jnbr** [comment] 2018-11-13 19:35
this are at least two different bugs:

for `kitty` and most recently built packages, the problem is that the order of entries in `files.plist` was changed in 3ef932de2f86b239bc7b0d5d3b8784b3c2ebdb74. This change requires to remove the directories listed in `files.plist` in reverse order.

`faenza-icon-theme` was built `2015-08-05 13:56 UTC`, way before the change. `xbps-remove --debug faenza-icon-theme` complains about modified symlinks and leafs them in place.

**Comment by xtraeme** [comment] 2019-05-14 07:55
This should be fixed in master, see #31

**Comment by jnbr** [comment] 2019-05-14 08:42
second part of this issue about not removing symlinks is still unsolved (see `faenza-icon-theme` as example)

**Comment by xtraeme** [comment] 2019-05-14 08:45
Looking into it

**Comment by xtraeme** [comment] 2019-05-14 08:56
I see what's happening:

```
│       ├── icons
│       │   ├── Faenza
│       │   │   ├── actions
│       │   │   ├── apps
│       │   │   │   ├── 64
│       │   │   │   │   └── mailnag.png -> ./mail-notification.png
```

Those symlinks were not removed due to `./`.

**Closed** 2019-06-07 18:13 UTC

**Comment by biopsin** [comment] 2019-09-21 08:19
gcc does not cleanup after upgrades.. all folders are empty for gcc < 9.2

/usr/lib/gcc/tree -d

> └── x86_64-unknown-linux-gnu
>     ├── 7.3
>     │   ├── include
>     │   ├── include-fixed
>     │   ├── install-tools
>     │   └── plugin
>     │       └── include
>     │           ├── ada
>     │           └── config
>     ├── 8.2
>     │   ├── include
>     │   ├── install-tools
>     │   └── plugin
>     │       └── include
>     │           ├── ada
>     │           └── config
>     ├── 8.3
>     │   └── include
>     ├── 9.1
>     │   └── include
>     ├── 9.2
>     │   ├── include
>     │   │   ├── sanitizer
>     │   │   └── ssp
>     │   ├── include-fixed
>     │   │   └── bits
>     │   ├── install-tools
>     │   │   └── include
>     │   └── plugin
>     │       └── include
>     │           ├── c-family
>     │           ├── config
>     │           │   └── i386
>     │           ├── cp
>     │           ├── d
>     │           └── objc
>     └── 9.2.0 -> 9.2

**Comment by juipeltje** [comment] 2023-12-01 16:20
does this issue still exist? i was making a template for an icon theme and noticed when i uninstalled the package, it deletes everything except the folder that the icon theme was in in /usr/share/icons/. it just leaves behind empty folders. i thought something was wrong with my template, but i decided to test it and download a random icon theme from the repo (paper-icon-theme) and after removing it again it does the same thing. it leaves the empty folders behind.
