### ISSUE TITLE
Hook system feature request

### ISSUE THREAD

**Issue by pandom79** [void-linux/xbps#332] opened 2020-09-09 08:15 UTC
Hi guys,

would it be possible to have a hooking system in xbps in the future?
To explain me better, a system like the one used in pacman that uses [alpm-hooks](https://www.archlinux.org/pacman/alpm-hooks.5.html):

```
[Trigger] (Required, Repeatable)
Operation = Install | Upgrade | Remove (Required, Repeatable)
Type = Path | Package (Required)
Target = <Path | PkgName> (Required, Repeatable)

[Action] (Required)
Description = ... (Optional)
When = PreTransaction | PostTransaction (Required)
Exec = <Command> (Required)
Depends = <PkgName> (Optional)
AbortOnFail (Optional, PreTransaction only)
NeedsTargets (Optional)
```

It would be very useful for us.

Regards

**Comment by Duncaen** [comment] 2020-09-09 11:25
Duplicate of https://github.com/void-linux/xbps/issues/304.

**Closed by Duncaen** 2020-09-09 11:25 UTC
